### ISSUE TITLE
ForkedTransaction与TaggedTransaction的用途

### ISSUE THREAD

**Issue by inversionhourglass** [chinaboard/PureCat#4]
您好，最近开始接触cat项目，现在再看您这边的.NET客户端的源码，整体看得懵懵懂懂。对于ForkedTransaction和TaggedTransaction就不理解了，对于从ITransaction中继承而来的Standalone属性也不是很明白。还望解答，感谢！

**Comment by chinaboard** [comment]
ForkedTransaction和TaggedTransaction都是Transaction的一个变种，前者是Fork的某个Transaction，后者是打了一个tag的Transaction
Standalone没有什么需求的话不需要关心
