### ISSUE TITLE
DefaultMessageManager下TruncateAndFlush方法代码问题

### ISSUE THREAD

**Issue by inversionhourglass** [chinaboard/PureCat#5]
在该方法中，最后的代码有点问题：
`
_mTree.MessageId = childId;
_mTree.ParentMessageId = tree.MessageId;
`
第二句赋值存在问题，在方法的开始，有`IMessageTree tree = _mTree;`，也就是tree与_mTree是相同引用。所以上面的两次赋值，实际都是childId。

我查看了一下java的源码，赋值方式有点区别
`
ctx.m_tree.setMessageId(childId);
ctx.m_tree.setParentMessageId(id);
`

**Comment by chinaboard** [comment]
这个是由于我当时对照java代码的时候顺手优化了一段逻辑导致的，如果改变 _mTree.MessageId = childId; _mTree.ParentMessageId = tree.MessageId; 两者的赋值顺序就可以避免这个问题。后续会参照ctrip的代码把整体再重构一下。
