### ISSUE TITLE
你封装的CAT.NET那块东西呢？

### ISSUE THREAD

**Issue by chimisu** [chinaboard/PureCat#6]
哥们，公司最近打算也用CAT。我看你向点评的CAT.NET项目提交过，怎么你这里没有Web那块呢？能放出来么？

**Comment by chinaboard** [comment]
http串联那一块吗，一般都是自行实现的，有需求的话我这边找个时间也可以写一下放出来。

**Comment by chimisu** [comment]
@chinaboard 放出来吧。数据访问底层那块，比如SQLHelper，用CAT.NET应该怎么搞？有思路嘛？

**Comment by chinaboard** [comment]
sql的埋点如果你用的不是mysql，如果要看依赖，需要自己更改cat服务器端的代码解析DatabaseName，具体见[DatabaseParser.java](https://github.com/dianping/cat/blob/master/cat-consumer/src/main/java/com/dianping/cat/consumer/dependency/DatabaseParser.java)

**Comment by chinaboard** [comment]
见[sql demo](https://github.com/chinaboard/PureCat/commit/7578d8e40805cf4745f52baf7c41b92d16090e94)
