### ISSUE TITLE
CAT是否不适用于.NET异步编程（async/await）

### ISSUE THREAD

**Issue by inversionhourglass** [chinaboard/PureCat#7]
CAT的思想是一个线程一个操作对应CAT的一个Context，而.NET的异步编程是让你像写同步代码一样写异步代码，一个方法作为一个操作，但是使用await的前后会分为两个线程，这就将一个操作分到多个线程中完成。

虽然CAT提供了ForkedTransaction可以关联多个线程，但是使用ForkedTransaction就需要把一个方法拆分到多个ForkedTransaction中，这样出来的统计很不直观，而且这需要在每个await的前后进行手动埋点，很难通过框架直接封装掉。

我觉得.NET异步编程的思想与CAT本身的概念是冲突的，请教一下作者对这个有什么看法，有没有什么解决方案。

**Comment by chinaboard** [comment]
虽然不是作者，但是关于.net异步使用cat这一块我个人的经验是能做在框架里的都做在框架里，做不了的就手动打埋点，cat这种客户端生成log的话对应起来没什么特别好的方式。
除非是log全部打到远程，然后通过计算汇总出真正的调用链。

**Comment by inversionhourglass** [comment]
你说的log达到远程是什么概念的？

cat应用于.NET异步编程的时候存在这样几个问题：
1.await前后会切换线程，同一个方法无法使用一个transaction进行包装
```C#
static async Task M()
{
    var tran = Cat.NewTransaction("t", "t");
    SyncOperation1();
    await M1();
    SyncOperation2();
    await M2();
    SyncOperation3();
    await M3();
    SyncOperation4();
    tran.Complete();
}
```
上面的代码中，tran对象调用Complete方法是无法完成Complete的，因为创建tran的线程与Complete的线程不是同一个，Complete时找不到Context（也有可能能够complete，当M3await返回时，从线程池中刚好拿到了之前创建tran的那个线程，但一般情况是不能Complete的）。
对于这种情况有两种方式解决，第一种是在每次await切换线程前将transaction完成，这种方式会将M方法拆分成多个transaction，并且直接交由cat服务端是无法统计出方法M的实际耗时；第二种是修改cat底层，将ThreadLoacl进行替换（我现在用的CallContext），这种方式可以解决现在说的这种情况。但考虑下面这种情况：
```C#
static async Task M()
{
    var tran = Cat.NewTransaction("t", "t");
    SyncOperation1();
    var t1 = M1();
    SyncOperation2();
    var t2 = M2();
    await Task.WhenAll(t1, t2);
    SyncOperation3();
    await M3();
    SyncOperation4();
    tran.Complete();
}
```
所有异步方法在调用后直接await时，能够保证代码的运行顺序与你编写的顺序相同（微软的异步编程就是让开发像写同步代码一般编写异步代码），但是当使用Task.WhenAll时，代码的运行就存在了并行运行，此时CAT就无法进行埋点。

注意，M1、M2..这种方法并不是在进入方法时就开始异步，而是在调用到最底层的await io操作时才异步返回，所以不能讲M1这种方法直接作为一个ForkedTransaction，因为它占用了同步耗时。

现在我这边改的只有Task.WhenAll这种情况无法处理。

**Comment by chinaboard** [comment]
有种比较简单粗暴的方式，在M1和M2里也做Transaction，调用时构建2个子catid传进去做调用链串联

**Comment by inversionhourglass** [comment]
不行的，在没使用Task.WhenAll而直接在每个异步调用的时候直接await，那么使用DefaultTransaction就能够串联起来，但如果使用了Task.WhenAll，那么使用哪种Transaction都是不对的。
你说的这种方式，就是ForkedTransaction，这种方式就代表将M1和M2整体都作为异步执行的，但实际上异步的开始是在最底层调用await io操作时才开始的。你这种方式最后统计出来的耗时的不对的。

**Comment by chinaboard** [comment]
不是ForkedTransaction，你可以测试一下做串联
[https://github.com/chinaboard/PureCat/tree/master/PureCat.Demo](https://github.com/chinaboard/PureCat/tree/master/PureCat.Demo)
跑一下看看效果

**Comment by inversionhourglass** [comment]
你给的这个是多线程示例，这个直接通过ForkedTransaction就可以了，remoteCall是用于服务之间的调用的。异步编程与多线程差别还是挺大的。

**Comment by chinaboard** [comment]
我只是用多线程演示了一下服务间的串联，只是说这个可以解决你说的那个事情，但是看起来会比较奇怪

**Comment by inversionhourglass** [comment]
这个不行的，remotecall和forked是一个原理，都是通过messageid进行关联，只是remotecal在服务端有特殊处理，会进行统计分析，在cross里面可以看到汇总的调用情况。这两个都是解决不了我说的这种情况。

不论是remotecall还是forked，都是并行执行一个相对完整的操作，统计出来的耗时是针对这个操作的，但是async/await的不同。

你可以试试，你会发现很多问题。

**Comment by chinaboard** [comment]
我也没有特别好的思路，但是有2点
1、业内的一些APM方案是埋点后，将数据丢到spark汇总计算
2、.net这种情况，通过CLR的COM注入的方式来做会不会更可行一些（风险大）

**Comment by inversionhourglass** [comment]
嗯，现在用的是CAT，所以想在不更改CAT的数据结构的情况下进行改造，但是发现CAT数据结构和.NET的异步编程有些冲突，虽然也可以想办法将数据分散记录，但是就没办法直接用CAT现有的数据分析器进行分析个归档了。

感谢回答，点评提供的.NET版本太阉割了，很多java版本有的，.NET版本并没有，一直用的你这个版本。

**Comment by chinaboard** [comment]
[https://github.com/ctripcorp/cat.net](https://github.com/ctripcorp/cat.net)
ctrip也维护了一份，好像开源的没我这个早吧，欢迎提PR，一直没太多的时间维护这个
